apiVersion: v1
kind: ConfigMap
metadata:
  name: notification
data:
  server-host: "0.0.0.0"
  server-port: "80"
  vapid-subscriber: "mailto:dev@vultisig.com"
  certificate: "/etc/notification/sandbox.p12"
  production: "false"
  vapid-public-key: "BP0Bxc6TYi5-zzB2MEieTbqlKgMkvcY6p1epLnnQ2U9DSap6emmdWn3RqqnkzqJnoys8kZ9dTaAmmAoiMoj5vi4"